### PR TITLE
ayyyy useless pr

### PR DESCRIPTION
**Pull request by capslock321**
gib lavalink more GB of Ram

### CODE REVIEW

**Comment by BobDotCom** [comment]
Im not sure exactly what this does, could you explain this a bit? im not very familiar with java

**Comment by capslock321** [comment]
It gives java more ram to operate on, in theory your run up script now is fine, but this allocates more ram to lavalink for it to work on.

**Comment by BobDotCom** [comment]
Makes sense. currently the machine I am running it on only has 2GB of ram total. I will be switching to a new machine with 4GB soon, but in the meantime will this cause any issues?

**Comment by capslock321** [comment]
no it should not, i just want a pr to get thru tbh

**Comment by BobDotCom** [comment]
lol ok, other than that it looks fine so wish granted

**Comment by capslock321** [comment]
yay hopefully i did not fk up, it works in my jar file

**Comment by BobDotCom** [comment]
Ok. If you join my support server (iirc the link is in the README), you can get a special contributor role, just dm to claim if you want.

**Pull request merged**
